# Generated by Django 5.0 on 2025-09-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movierequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieRequest',
        ),
    ]
