# Generated by Django 5.0 on 2025-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviepetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepetition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
